export FERMI_HDFS_MASTER_IP=0.0.0.0
export FERMI_HDFS_MASTER_PORT=9000
export FERMI_HDFS_DIR=/user/hadoop/input/
export FERMI_PROJECT_DIR=/home/
export FERMI_SPARK_MASTER_IP=0.0.0.0
export FERMI_SPARK_MASTER_PORT=7077